name: distance
author: vu-ase
source: https://github.com/VU-ASE/distance
version: 1.2.0
description: A small service that gets the distance measured by the ultrasound and outputs it as a stream

commands:
  build: make build
  run: ./bin/distance

inputs: []

outputs: 
  - distance # in meters

configuration: 
  - name: polling-delay
    type: number
    value: 20 # ms
    tunable: false
