name: distance
author: vu-ase
source: SERVICE_SOURCE
version: 1.0.0
description: The distance service

commands:
  build: make build
  run: ./bin/distance

inputs: []

outputs: 
  - distance-cm

configuration: 
  - name: polling-delay
    type: number
    value: 20 # ms
    tunable: false
