# Service definition
name: distance
description: Outputs the distance to an object

# No dependencies
dependencies: []

# Outputs actuation
outputs:
  - name: distance
    address: tcp://localhost:5587

# Runtime options
options:
  - name: polling-delay
    type: int
    mutable: false
    default: 20 # ms
